CREATE TABLE countdown (
	id INT(1) UNSIGNED NOT NULL AUTO_INCREMENT,
	name VARCHAR(64) NOT NULL,
	story VARCHAR(300) COLLATE utf8_unicode_ci NOT NULL,
	expiration DATETIME NOT NULL,
	PRIMARY KEY (id),
	INDEX (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
